#!/bin/sh

MSG_TPL="\e[32m%s\e[39m\n"
REPO_ROOT_DIR=$(git rev-parse --show-toplevel)

if [ -z "${REPO_ROOT_DIR}" ]; then
    printf "\e[1;31mWARNING: \e[0;31mThis operation must be run at the root the repository (where the .git directory is).\n"
fi

printf "$MSG_TPL" "Installing hooks..."
rm "${REPO_ROOT_DIR}"/.git/hooks/pre-commit
rm "${REPO_ROOT_DIR}"/.git/hooks/post-merge
ln -sv "${REPO_ROOT_DIR}"/tools/hooks/pre-commit "${REPO_ROOT_DIR}"/.git/hooks/pre-commit
ln -sv "${REPO_ROOT_DIR}"/tools/hooks/post-merge "${REPO_ROOT_DIR}"/.git/hooks/post-merge

printf "$MSG_TPL" "Installing Commit Template"
git config commit.template "${REPO_ROOT_DIR}"/tools/hooks/commit.template

exit 0
