#!/bin/sh

REPO_ROOT_DIR=$(git rev-parse --show-toplevel)
REPO_FOLDER=${PWD##*/}
FILES_CHANGED=$(git diff --cached --name-status --diff-filter=ACMRTUXB |awk '{print ($NF)}' | grep -E '\.php|\.yml|\.feature$')
JSON_FILES_CHANGED=$(git diff --cached --name-status --diff-filter=ACMRTUXB |awk '{print ($NF)}' | grep -E '^schemas/')
MSG_TPL="\e[32m%s\e[39m\n"

if [[ -n $JSON_FILES_CHANGED ]]; then

    printf "$MSG_TPL" "Checking jsonlint installation"
    hash jsonlint || npm install jsonlint -g

    printf "$MSG_TPL" "Running jsonlint"
    for file in $JSON_FILES_CHANGED
    do
        jsonlint --indent="    " --in-place "$file" || exit 1
    done
fi

if [[ -n $FILES_CHANGED ]]; then

    printf "$MSG_TPL" "Running PHP Lint"
    for file in $FILES_CHANGED
    do
        php -l "$file" || exit 1
    done

    printf "$MSG_TPL" "Running PHP-CS-Fixer"
    CONFIG_FILE=.php_cs

    if [ ! -e $CONFIG_FILE ];
    then
        echo "$CONFIG_FILE does not exist. Please configure php-cs-fixer."
        exit 1
    fi

    for file in $FILES_CHANGED
    do
        "${REPO_ROOT_DIR}"/vendor/bin/php-cs-fixer fix "$file" --verbose --config=$CONFIG_FILE
        git add "$file";
    done

    printf "$MSG_TPL" "Running PHPUnit on $REPO_FOLDER"
    "${REPO_ROOT_DIR}"/vendor/bin/phpunit || exit 1

fi
